-- noinspection SqlNoDataSourceInspectionForFile

ALTER TABLE TEST.EMPLOYEE
  ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES TEST.DEPARTMENT (DEPARTMENT_ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE TEST.EMPLOYEE
  ADD FOREIGN KEY (POSITION_ID) REFERENCES PUBLIC.POSITION (POSITION_ID) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE PUBLIC.EMPLOYEE_SKILL
  ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES TEST.EMPLOYEE (EMPLOYEE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PUBLIC.EMPLOYEE_SKILL
  ADD FOREIGN KEY (SKILL_ID) REFERENCES PUBLIC.SKILL (SKILL_ID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX NAME_IDX
  ON TEST.EMPLOYEE (LAST_NAME ASC, FIRST_NAME DESC);